services:
  - type: web
    name: whatsapp-chatbot
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn app.main:app --host 0.0.0.0 --port 10000
    plan: free
    envVars:
      - key: TWILIO_ACCOUNT_SID
        value: ${TWILIO_ACCOUNT_SID}
      - key: TWILIO_AUTH_TOKEN
        value: ${TWILIO_AUTH_TOKEN}
      - key: TWILIO_WHATSAPP_NUMBER
        value: ${TWILIO_WHATSAPP_NUMBER}
      - key: OPENAI_API_KEY
        value: ${OPENAI_API_KEY}
      - key: MONGODB_URI
        value: ${MONGODB_URI}
      - key: DATABASE_NAME
        value: chatbotdb
      - key: FIREBASE_CREDENTIALS_PATH
        value: /etc/secrets/firebase.json 